
# Всё из этого файла получается только при запуске server.js
# Если вы изменили что-то во время его работы, перезапустите его
[logs]

do_get_log = true # Делать ли логи GET запросов? (true - да, false - нет, по умолчанию true)
get_frequency = 120 # Частота логов GET запросов в секундах (минимум 5, 120 - по умолчанию)
